#!/bin/bash
#ipbc - Inter Planetary Bash Chat
## "Post" message
if [ ! -z "$1" ]
then
	resolved=$(ipfs key list -l | grep relay-ipbc-key | awk '{print $1}' | sed -e 's/\/ipfs\///g')
	previous=$(ipfs name resolve $resolved)
	message=$(echo "$1" | ipfs add -q)
	ipfs name publish --key=relay-ipbc-key $( echo "{\"message\":\"$message\",\"previous\":\"$previous\"}" | ipfs add -q )
fi
