#!/bin/bash
# ipbc - Inter Planetary Bash Chat
while true
do
	while IFS="" read -r p || [ -n "$p"]
	do
		if [ ! $p == '' ]
		then
			check="$(ipfs name resolve $p)"
			if [ ! "$check"  == "$latest" ]
			then
				from="$p"
				message="$(ipfs cat /ipns/$p | json_pp |  sed -e 's/{//g' | sed -e 's/}//g' | sed -e 's/":"/=/g' | sed -e 's/"//g' | sed -e 's/,//g' | sed -e 's/ //g' | grep message | sed -e 's/message://')"
				latest="$(ipfs name resolve $p)"
				echo "$p : $(ipfs cat $message)"
			fi
		else
			break
		fi
	done < ~/following-ipbc-keys
	sleep 10
done
